version: 2.1

# Define all jobs
jobs:
  lint:
    docker:
      - image: cimg/php:7.4.29-node
    steps:
      - checkout
      - run:
          name: Install project dependencies
          command: composer install && npm ci
      - run:
          name: Run phpcs linting
          command: vendor/squizlabs/php_codesniffer/bin/phpcs -s --standard=phpcs.ruleset.xml .
      - run:
          name: Run eslint
          command: npm run lint:js
      - run:
          name: Run stylelint
          command: npm run lint:css


# Define workflows
workflows:
  precommit_testing:
    jobs:
      - lint
